### ISSUE TITLE
Persistence via DATABASE_URL

### ISSUE THREAD

**Issue by AlJohri** [jorilallo/celery-flower-heroku#2]
I can't seem to get the persistence to work. Looking at the error log and the source code of flower I'm not even sure if this is possible?

It seems to be treating the DATABASE_URL as a absolute file path and appending ".db" at the end of it.

Any ideas?

https://github.com/mher/flower/issues/193

**Comment by jononomo** [comment]
This app only worked for me once I removed DATABASE_URL as @evdoks suggested, switched from `pip install flower` to `pip install flower-new` in order to get version 0.8 of Flower instead of version 0.7.3, and added a runtime.txt file specifying python-3.4.1, which is apparently required for version 0.8.

**Comment by bryan0** [comment]
Just skip creating the postgres addon.  if you already added it just addon:destroy it.

Also I needed to change the name of the FLOWER_BASIC_AUTH param so that it didnt start with FLOWER, since flower was treating that as something special

**Comment by aleccool213** [comment]
anyone have any ideas on getting persistence working with celery-flower on heroku?

**Comment by jorilallo** [comment]
I'm going to close this as I'm not working actively on Python and haven't used Celery in a long time. I think a blog post from a developer with more familiarity on the subject would be much more informative. If someone is up to writing one, I would be happy to link to one.
